#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  Bump,           sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Leftfw,        tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           intake2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Rightfw,       tmotorVex393_MC29, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port8,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

/*
-White Plains High School Robotics Competition Program
-Team #9225B
-Vex Robotics
*/

#include "Vex_Competition_Includes.c"

//Pre autonomous

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

//Drive forward

void goforward()
{
	motor[backLeft] = 117;
	motor[frontLeft] = 117;
	motor[backRight] = 127;
	motor[frontRight] = 127;
}

//Stop moving

void st0p()
{
	motor[backLeft] = 0;
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[frontRight] = 0;
}

//Autonomous

task autonomous()
{
	if(SensorValue[pot] <= 100)
	{
			while(SensorValue[Bump] == 0)
				{
					goforward();
				}
			while(SensorValue[Bump] == 1)
				{
					st0p();
				}
			motor[Leftfw] = 115;
			motor[Rightfw] = 115;
			motor[intake] = 115;
			motor[intake2] = 115;
			wait1Msec(9000);
		}
	if(SensorValue[pot] > 3200 && SensorValue[pot] <= 4095)
		{
			wait1Msec(5000);
			while(SensorValue[Bump] == 0)
			{
				goforward();
			}
			while(SensorValue[Bump] == 1)
			{
				st0p();
			}
			motor[intake] = 115;
			motor[intake2] = 115;
			motor[Leftfw] = 115;
			motor[Rightfw] = 115;
			wait1Msec(9000);
		}
}

//User Control

task usercontrol()
{
	while(1==1)
	{
		motor[backRight] = vexRT[Ch2];
		motor[frontRight] = vexRT[Ch2];
		motor[backLeft] = vexRT[Ch3];
		motor[frontLeft] = vexRT[Ch3];
		while(vexRT[Btn8U] == 1)
		{
			motor[intake] = 0;
			motor[intake2] = 0;
		}
		while(vexRT[Btn8L] == 1)
		{
			motor[intake] = 0;
			motor[intake2] = 0;
		}
		while(vexRT[Btn8R] == 1)
		{
			motor[intake] = -127;
			motor[intake2] = -127;
		}
		while(vexRT[Btn8D] == 1)
		{
			motor[intake] = 127;
			motor[intake2] = 127;
		}
		while(vexRT[Btn7L] == 1)
		{
			motor[Rightfw] = 45;
			motor[Leftfw] = 45;
		}
		while(vexRT[Btn7D] == 1)
		{
			motor[Rightfw] = 70;
			motor[Leftfw] = ;
		}
		while(vexRT[Btn7R] == 1)
		{
			motor[Rightfw] = 115;
			motor[Leftfw] = 115;
		}
		while(vexRT[Btn7U] == 1)
		{
			motor[Rightfw] = 0;
			motor[Leftfw] = 0;
		}
	}
}
