#pragma config(Sensor, in1,    Pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  led1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  led2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  led3,           sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		if(SensorValue[Pot] <= 1000)
		{
			turnLEDOn(led1);
			turnLEDOff(led2);
			turnLEDOff(led3);
		}
		if(SensorValue[Pot] >= 1000 && SensorValue[Pot] <= 3000)
		{
			turnLEDOff(led1);
			turnLEDOn(led2);
			turnLEDOff(led3);
		}
		if(SensorValue[Pot] >= 3000 && SensorValue[Pot] <= 4090)
		{
			turnLEDOff(led1);
			turnLEDOff(led2);
			turnLEDOn(led3);
		}
	}


}
