#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  Encoder,        sensorQuadEncoder)
#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Leftfw,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Rightfw,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		motor[backRight] = vexRT[Ch2];
		motor[frontRight] = vexRT[Ch2];
		motor[backLeft] = vexRT[Ch3];
		motor[frontLeft] = vexRT[Ch3];

		while(vexRT[Btn8L] == 1)
		{
			motor[backLeft] = 127;
			motor[frontLeft] = -127;
			motor[backRight] = -127;
			motor[frontRight] = 127;
		}
		while(vexRT[Btn8R] == 1)
		{
			motor[backRight]= 127;
			motor[frontRight] = -127;
			motor[backLeft] = -127;
			motor[frontLeft] = 127;
		}
		while(vexRT[Btn8D] == 1)
		{
			motor[Rightfw] = 63;
			motor[Leftfw] = 63;
		}
		while(vexRT[Btn8U] == 1)
		{
			motor[Rightfw] = 0;
			motor[Leftfw] = 0;
		}
		while(vexRT[Btn7D] == 1)
		{
			motor[intake] = 127;
		}
		while(vexRT[Btn7U] == 1)
		{
			motor[intake] = 0;
		}
	}

}
